In [1]:
import numpy as np

In [3]:
list_data = [1,2,3,4,5]
arr_from_list = np.array(list_data)
print("Array from list:",arr_from_list)

Array from list: [1 2 3 4 5]


In [5]:
type(arr_from_list)

numpy.ndarray

In [6]:
arr_zeros = np.zeros((2,3))
print("\nArray of zeros:\n",arr_zeros)


Array of zeros:
 [[0. 0. 0.]
 [0. 0. 0.]]


In [10]:
arr_ones = np.ones((2,3))
print("\nArray of ones:\n",arr_ones)


Array of ones:
 [[1. 1. 1.]
 [1. 1. 1.]]


In [11]:
arr_ones.shape

(2, 3)

In [12]:
arr_ones.ndim

2

In [13]:
np.arange(5,15,2)

array([ 5,  7,  9, 11, 13])

In [16]:
np.linspace(5,15,10)

array([ 5.        ,  6.11111111,  7.22222222,  8.33333333,  9.44444444,
       10.55555556, 11.66666667, 12.77777778, 13.88888889, 15.        ])

In [17]:
#indexing and slicing
arr = np.array([10,20,30,40,50,60,70])
print("Element at index 2:",arr[2])

Element at index 2: 30


In [18]:
sliced_arr = arr[2:5]
print("Sliced array (index 2 to 4):",sliced_arr)

Sliced array (index 2 to 4): [30 40 50]


In [19]:
arr[::2]

array([10, 30, 50, 70])

In [23]:
arr_2d = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(arr_2d[0:2,1:3])  # Accessing element at row 1, column 2

[[2 3]
 [5 6]]


In [28]:
indices = np.array([0,2])
arr_2d[indices,0:2]  # Accessing elements at index 0 and 2

array([[1, 2],
       [7, 8]])

In [29]:
bool_mask = arr_2d > 5
arr_2d[bool_mask]  # Elements greater than 5

array([6, 7, 8, 9])

In [30]:
matrix = np.arange(1,13)
matrix 

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [31]:
matrix = matrix.reshape(3,4)
matrix

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [32]:
raveled = matrix.ravel()

In [34]:
transposed = matrix.transpose()
transposed

array([[ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11],
       [ 4,  8, 12]])

In [35]:
arr_float = np.array([1.2,3.14,5.6])
print("array:",arr_float)
print(arr_float.dtype)

array: [1.2  3.14 5.6 ]
float64


In [38]:
arr_int = arr_float.astype(np.int64)
print(arr_int)
print(arr_int.dtype)

[1 3 5]
int64


In [4]:
#Arithmetic functions
x = np.array([1,2,3,4])
y = np.array([10,20,30,40])

print("Add:", np.add(x,y))
print("subtract:", np.subtract(x,y))
print("Divide:", np.divide(x,y))
print("Multiply:",np.multiply(x,y))

Add: [11 22 33 44]
subtract: [ -9 -18 -27 -36]
Divide: [0.1 0.1 0.1 0.1]
Multiply: [ 10  40  90 160]


In [6]:
arr_for_log =np.array([1,np.e,100])
arr_for_log

array([  1.        ,   2.71828183, 100.        ])

In [7]:
np.log(arr_for_log)

array([0.        , 1.        , 4.60517019])